"==================================================
""                my vimrc
"==================================================
"
"" general setting
set backspace=2
set linebreak
set whichwrap=b,s,<,>,[,]
set listchars=tab:.\ ,trail:-
set hidden
set scrolloff=7
set ignorecase
set noerrorbells
set novisualbell
set t_vb=
set wildmenu
set list
set showmatch
set mat=1 "match time
set smartindent
set shiftwidth=2
set autoindent
set completeopt=longest,menu
set autoread
set gdefault
" status setting
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
set laststatus=2
set ruler
let mapleader='\'
set sessionoptions-=curdir
set sessionoptions+=sesdir

set undofile

filetype off                   " required!


" let Vundle manage Vundle
" required! 

" My Bundles here:
set rtp+=~/.vim/bundle/Vundle.vim,~/.vim/bundle/YouCompleteMe
call vundle#begin()
"
" original repos on github
"Bundle 'scrooloose/syntastic'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'davidhalter/jedi-vim' 
"Plugin 'fatih/vim-go'
"Bundle 'Lokaltog/vim-easymotion'
"Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
"Bundle 'scrooloose/syntastic'
" vim-scripts repos
"Bundle 'L9'
"Bundle 'FuzzyFinder'
" ...
call vundle#end()


filetype plugin indent on     " required!


"
" General programming setting
"
syn on
filetype plugin on
filetype indent on
"cscope setting
autocmd Filetype c,cpp,cc set cinoptions=l1
autocmd Filetype c,cpp,cc let c_gnu=1
autocmd FileType c,cc,cpp,yacc,lex,tcl set shiftwidth=2 | set expandtab | set softtabstop=2
autocmd FileType asm set shiftwidth=8 | set expandtab | set softtabstop=8

syn match Braces display '[{}()\[\]]'
hi Braces ctermfg=blue

" Send more characters for redraws
set ttyfast
"
" " Enable mouse use in all modes
set mouse=r
"
" " Set this to the name of your terminal that supports mouse codes.
" " Must be one of: xterm, xterm2, netterm, dec, jsbterm, pterm
set ttymouse=xterm2

set viminfo='10,\"100,:20,%,n~/.viminfo
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" jedi configuration
let g:jedi#show_call_signatures = "1"

imap jj <Esc>
