#!/bin/bash

wait_timeout()
{
  local p=$1
  echo "wait for PID $p, cmd = "
  cat /proc/$p/cmdline
  echo
  local timeout=$2
  while [ $timeout -ne 0 ]; do
    sleep 1
    if ! test -d /proc/$p ; then
      echo "PID $p finishes"
      break
    fi
    timeout=$((timeout-1))
  done
  if test -d /proc/$p ; then
    echo "PID $p timeout, kill" 
    kill -KILL $p
  fi
}
